# -------------------------------
# name:  vagrantfile (vm_base)
# autor: jdelchiaro - Grupo6
# date:  18/02/2016
# -------------------------------

Vagrant.configure(2) do |base|

    base.vm.box = "ubuntu/trusty64"
  
    base.vm.provision :shell, path: "install.sh"
    base.vm.provision :shell, path: "keys.sh"
    base.vm.provision :shell, path: "init.sh"      
    base.vm.network :forwarded_port, guest: 101, host: 1001    
    
    base.ssh.username = 'vagrant'
    base.ssh.password = 'vagrant'
    base.ssh.insert_key = 'true'  
    
    base.vm.network "forwarded_port", guest: 80, host: 8080
    
    base.vm.network "private_network", type: "dhcp"
    base.vm.synced_folder "repositorio/", "/home/vagrant"
    
end
