# -------------------------------
# name:  vagrantfile(vm_dock) Principal para docker-engine
# autor: jdelchiaro - Grupo6
# date:  18/02/2016
# -------------------------------

Vagrant.configure(2) do |dock|

    dock.vm.box = "ubuntu/vivid64" 
    dock.vm.provision :shell, path: "install.sh"
    dock.vm.provision :shell, path: "keys.sh"
    
    dock.vm.network :forwarded_port, guest: 100, host: 1000
    
    dock.ssh.username = 'vagrant'
    dock.ssh.password = 'vagrant'
    dock.ssh.insert_key = 'true'
  
    dock.vm.box_check_update = false
  
    dock.vm.network "private_network", type: "dhcp"  
    # dock.vm.network "forwarded_port", guest: 80, host: 8080  
    # dock.vm.network "private_network", ip: "192.168.33.10"   
    # dock.vm.network "public_network"
    
    dock.vm.synced_folder "repositorio/", "/home/vagrant"
    
    dock.vm.provider "virtualbox" do |vb|  
    
        vb.gui = true
        #vb.customize ["modifyhd", :id, "--resize", 100000]
        vb.memory = "2048"
        vb.cpus = 2
    end
end

